iptables: simplify flush script

diff --git a/scripts/iptables-flush b/scripts/iptables-flush
--- a/scripts/iptables-flush
+++ b/scripts/iptables-flush
@@ -1,22 +1,18 @@
 #!/bin/bash
-# Usage: iptables-flush [-6]
+#
+# Usage: iptables-flush [6]
+#
 
-iptables=/usr/sbin/iptables
-tables=(filter mangle raw)
-
-if [[ "$1" == "-6" ]]; then
-  iptables=/usr/sbin/ip6tables
-else
-  # Only ipv4 has a nat table
-  tables+=(nat)
+iptables=ip$1tables
+if ! type -p "$iptables"; then
+  echo "error: invalid argument"
+  exit 1
 fi
 
-for table in "${tables[@]}"; do
-  $iptables -t "$table" -F
-  $iptables -t "$table" -X
-done
+while read -r table; do
+  tables+=("/var/lib/$iptables/empty-$table.rules")
+done <"/proc/net/ip$1_tables_names"
 
-for chain in INPUT FORWARD OUTPUT; do
-  $iptables -P "$chain" ACCEPT
-done
-
+if (( ${#tables[*]} )); then
+  cat "${tables[@]}" | "$iptables-restore"
+fi
